# config that builds the env for the kuka shelf experiment
run:
  algorithm:
    load_model: False  
    model_path: ""  
    type: "PPO"
  train:
    num_envs : 16  
    logging: 0
    timesteps: 15000000 
    save_freq : 30000
    save_folder: "./models/weights"  
    save_name: "kukashelfexperiment_default"
  eval:
    max_episodes: -1  
    logging: 1  
    display_delay: 0.00416666666 
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: False

env:
  max_steps_per_episode: 1024  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  use_physics_sim: True
  gravity: [0, 0, -9.8]
  sim_step: 0.00416666666 
  sim_steps_per_env_step: 1 
  robots:
    - type: "KR16" 
      config:
        name: "kr16_1"
        base_position: [0, 0, 0]
        base_orientation: [0, 0, 0]
        resting_angles: [0, -135, 90, 0, 90, 0]
        control_mode: 0
        self_collision: False
      sensors:
        - type: "LidarSensorKR16"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: True
            indicator_buckets: 11
            ray_start: 0.01
            ray_end: 0.65
            ray_setup:
              #ee_forward: [1, 1]
              ee_cone: [2, 5]
              ee_side_circle: [7, 3]
              #ee_back_cone: [2, 5]
              upper_arm: [8, 4]
            indicator: True
      goal:
        type: "PositionCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 10
          reward_collision: -5
          reward_distance_mult: -0.01
          dist_threshold_start: 0.2
          dist_threshold_end : 0.01
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: "None"

  world:
    type: "KukaShelfExperiment"
    config:
      workspace_boundaries: [-3, 3, -3, 3, 0.0, 3]
      shelves:
        - position: [-0.725, -1.15, 0.51]
          rotation: [90, 0, 0]
        - position: [-0.725, 1.65, 0.51]
          rotation: [90, 0, 0]
      shelf_params:
        rows: 3
        cols: 4
        element_size: 0.35
        shelf_depth: 0.5
        wall_thickness: 0.01
      