# config that builds the env as Yifan had it
run:
  algorithm:
    load_model: False  
    model_path: ""  
    type: "PPO"
  train:
    num_envs : 16  
    logging: 0
    timesteps: 15000000 
    save_freq : 30000
    save_folder: "./models/weights"  
    save_name: "oldtestcases_default"
  eval:
    max_episodes: -1  
    logging: 1  
    display_delay: 0.00416666666 
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: False

env:
  max_steps_per_episode: 1024  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  use_physics_sim: True
  gravity: [0, 0, -9.8]
  sim_step: 0.00416666666 
  sim_steps_per_env_step: 1 
  robots:
    - type: "UR5" 
      config:
        name: "ur5_1"
        base_position: [0, -0.12, 0.5]
        base_orientation: [0, 0, 0]
        resting_angles: [0, 90, -30, -120, -80, 90]
        control_mode: 0
        self_collision: False
      sensors:
        - type: "LidarSensorUR5"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: True
            indicator_buckets: 6
            ray_start: 0
            ray_end: 0.3
            ray_setup:
              ee_forward: [1, 1]
              wrist3_circle: [10, 10]
              wrist2_circle: [10, 10]
              wrist1_circle: [10, 10]
              upper_arm: [10, 10]
            indicator: True
      goal:
        type: "PositionCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 10
          reward_collision: -5
          reward_distance_mult: -0.01
          dist_threshold_start: 0.2
          dist_threshold_end : 0.01
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite:

  world:
    type: "Testcases"
    config:
      test_mode: 0  # randomly switch between all three test cases